# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "webkit_remote_unstable"
  s.version = "0.1.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Victor Costan"]
  s.date = "2014-03-23"
  s.description = "Launches Google Chrome instances and controls them via the Remote Debugging server"
  s.email = "victor@costan.us"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".travis.yml",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/webkit_remote_unstable.rb",
    "lib/webkit_remote_unstable/css.rb",
    "lib/webkit_remote_unstable/css_events.rb",
    "lib/webkit_remote_unstable/dom.rb",
    "lib/webkit_remote_unstable/page.rb",
    "test/fixtures/config.ru",
    "test/fixtures/html/css.html",
    "test/fixtures/html/dom.html",
    "test/fixtures/html/page.html",
    "test/helper.rb",
    "test/webkit_remote_unstable/css_test.rb",
    "test/webkit_remote_unstable/dom_test.rb",
    "test/webkit_remote_unstable/page_test.rb",
    "webkit_remote_unstable.gemspec"
  ]
  s.homepage = "http://github.com/pwnall/webkit_remote_unstable"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "2.0.14"
  s.summary = "Unstable features for the webkit_remote Webkit remote debugging client"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<webkit_remote>, [">= 0.5.3"])
      s.add_development_dependency(%q<bundler>, [">= 1.5.3"])
      s.add_development_dependency(%q<debugger>, [">= 1.6.6"])
      s.add_development_dependency(%q<jeweler>, [">= 2.0.1"])
      s.add_development_dependency(%q<minitest>, [">= 5.3.0"])
      s.add_development_dependency(%q<puma>, [">= 2.8.0"])
      s.add_development_dependency(%q<rack>, [">= 1.5.2"])
      s.add_development_dependency(%q<rack-contrib>, [">= 1.1.0"])
      s.add_development_dependency(%q<rdoc>, [">= 4.1.1"])
      s.add_development_dependency(%q<simplecov>, [">= 0.8.2"])
      s.add_development_dependency(%q<yard>, [">= 0.8.7.3"])
    else
      s.add_dependency(%q<webkit_remote>, [">= 0.5.3"])
      s.add_dependency(%q<bundler>, [">= 1.5.3"])
      s.add_dependency(%q<debugger>, [">= 1.6.6"])
      s.add_dependency(%q<jeweler>, [">= 2.0.1"])
      s.add_dependency(%q<minitest>, [">= 5.3.0"])
      s.add_dependency(%q<puma>, [">= 2.8.0"])
      s.add_dependency(%q<rack>, [">= 1.5.2"])
      s.add_dependency(%q<rack-contrib>, [">= 1.1.0"])
      s.add_dependency(%q<rdoc>, [">= 4.1.1"])
      s.add_dependency(%q<simplecov>, [">= 0.8.2"])
      s.add_dependency(%q<yard>, [">= 0.8.7.3"])
    end
  else
    s.add_dependency(%q<webkit_remote>, [">= 0.5.3"])
    s.add_dependency(%q<bundler>, [">= 1.5.3"])
    s.add_dependency(%q<debugger>, [">= 1.6.6"])
    s.add_dependency(%q<jeweler>, [">= 2.0.1"])
    s.add_dependency(%q<minitest>, [">= 5.3.0"])
    s.add_dependency(%q<puma>, [">= 2.8.0"])
    s.add_dependency(%q<rack>, [">= 1.5.2"])
    s.add_dependency(%q<rack-contrib>, [">= 1.1.0"])
    s.add_dependency(%q<rdoc>, [">= 4.1.1"])
    s.add_dependency(%q<simplecov>, [">= 0.8.2"])
    s.add_dependency(%q<yard>, [">= 0.8.7.3"])
  end
end

